name: Deploy to Dev

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy App Service to Dev
    uses: ./.github/workflows/.deploy_stack.yml
    with:
      environment_name: dev
      app_env: dev
      command: apply
    secrets: inherit
